orca-app/orca

scripts/dev.py, scripts/gles_gen.py
Without this, the build script tries to write to a specific output directory. This helps us use the script from our build.zig :^)
=> parametrize logfile in gles_gen.py

scripts/bindgen.py, src/platform/native_debug.c, src/platform/platform_debug.c, src/runtime.c, src/runtime.h, src/runtime_memory.c, src/wasmbind/core_api.json
This removes the dependency on `app/app.h` from `platform/native_debug.c`. This way we can pull subsets of the orca platform layer for native command line tools without having to pull all the app/windowing layer.
- Always log and abort normally from native code. 
- Display a dialog and exit silently when aborting/asserting from wasm code or bindings bound checks
=> Split runtime abort/asserts and wasm app abort/assert. 

src/graphics/gl_canvas.c
Fixes issue orca-app/orca#12
Every now and then while resizing the window, gl error 1281 gets printed. This does not cause any noticable issues to the program. However, other times a different error 1282 gets printed and my program freezes, no longer updating the viewport or responding to input. I tracked the issue down to oc_gl_grow_buffer_if_needed().  When this function is called with the path queues buffer from oc_gl_render_batch(), the second line of the function, `glBindBuffer(GL_SHADER_STORAGE_BUFFER, buffer);` causes the gl error. While debugging on my machine, this buffer handle is always 27.
I don't know enough about the orca system or opengl to track down why the glBindBuffer call is failing sometimes. However, I was able to fix the downstream effect of the runtime thread …
=> Fix runtime thread getting stuck in a loop on resize

scripts/dev.py
The motivation for these changes is to fix issues I ran into while updating the zig samples to live in an external repo. While we have a long-term plan to move the tooling away from python, this should unblock anyone trying to use the `orca bundle` commands for an external project in the near term, as well as anyone trying to build the zig samples.
=> Install script fixes

src/platform/osx_platform.c, src/platform/platform.h, src/platform/win32_platform.c
Minor syntax fix I ran into when I was doing zig bindings. The extra spacing changes are due to clang-format.
=> oc_get_host_platform() -> oc_get_host_platform(void)

src/graphics/gl_canvas.c
This patch fixes what seems like a copy-paste error that was causing crashes when drawing a large number of images. The calculation of copySize in `oc_gl_canvas_encode_path()`, which is the third parameter passed to `oc_gl_grow_input_buffer()`, was using eltCount instead of the intended pathCount. I fixed this and also added some guards in both of the encode functions to ensure that a newly calculated buffer capacity is always greater than eltCount or pathCount.
=> Fix buffer copySize calculation in oc_gl_canvas_encode_path

src/ui/ui.c, src/util/macros.h
* support size_t explicitly for non-MSVC platforms
* added casts in a couple places to ensure oc_clamp() deals with the same types
=> couple fixes for _Generic macro compile errors

.github/workflows/build-runtime.yaml, .github/workflows/build-tool.yaml, .github/workflows/create-release.yaml, scripts/dev.py
- Fixed build-tool script on mac
- Created a build-runtime workflow
- Created a create-release workflow that runs whenever a tag is pushed
- This builds the cli tool and the runtime for all currently supported platforms and creates a new release
I don't know how the self-hosted runner for mac arm64 works exactly, but it understandably doesn't run in my fork where I was developing. I believe it will only run in the base repo, so I haven't been able to test that yet.
I think this is at least a good start for getting CI working for the runtime and creating releases. This is my first time touching CI / github actions so please feel free to criticize or steer me in a different direction if anything feels off.
=> Get CI working for the runtime and create releases when tags are pushed

src/platform/platform_path.c
To ensure that there is a slash between the parent and relpath being appended, oc_path_append was checking the last character of parent and erroneously the LAST character of relpath for a slash. This fixes the error by checking the FIRST character of relpath instead.
=> fix oc_path_append

src/platform/win32_string_helpers.c
This commit fixes oc_win32_wide_to_utf8 so that it follows the convention that any string helper taking an arena as an argument will allocate and extra char and null terminate the string.
=> add null terminator in oc_win32_wide_to_utf8

src/tool/bundle.c
Updated bundle command to print a warning if image file passed as --icon argument does not exist.
Fixes issue #59
=> fix bundle command, no longer fails when icon file doesn't exist

src/graphics/wgpu_renderer.c
This toggles on the use of the new DXC shader compiler for compiling canvas shaders on Windows, which cuts startup time by around 50%.
=> Use DXC compiler in dawn D3D12 backend

samples/breakout/build.bat, samples/clock/build.bat, samples/fluid/build.bat, samples/triangle/build.bat, samples/ui/build.bat
The `build.bat` for each sample fails on Windows if orca sdk is in a path with spaces. This change allows paths with spaces.
=> Support whitespaces in sdk-path for Windows

sketches/check-bleeding/build.sh, sketches/check-bleeding/main.c, sketches/image/main.c, src/graphics/wgsl_shaders/raster.wgsl
Painting an image over a solid color rectangle would show some of the rectangle color bleeding through at the edges of the image of large upscaling factors.
My UV computation and filtering code was wrong, meaning we were sampling transparent pixels outside the texture when upscaling. This PR fixes these.  
Unfortunately, the wrong filtering also made the lack of mip-mapping less visible, because it was effectively doing some averaging of covered pixels. So this PR also makes this missing feature more visible, especially for large downscaling factors.  Proper downscaling should be addressed next.
=> Fix bleeding on image edges

Readme.md
Just a thing I noticed when trying to open the MacOS link of adding path variables. Otherwise it linked to the windows example for both versions
=> Fix mismatched link/description in Readme.md

src/ui/ui.c, src/ui/ui.h
Fixes #85 
Avoids having to use the explicit names and ruling system to restyle or interact with the boxes.
=> Add frame and textBox box to orca_ui_text_box_result

doc/mkdocs/docs/QuickStart.md
Fixed GitHub links to samples that were leading to 404
=> fix docs - links to correct sample

src/api.json, src/app/app.h, src/platform/platform_io.h
I can't find any cases where the first bit is reserved in the codebase, so I can only assume it was an oversight. 
Though if it was intentional I'd be curious to know why.
I've also taken the liberty of unifying the style for other bitmasks in the codebase, though that commit can be dropped if unwanted.
=> Utilize the first bit in File flags

src/ext/microtar/microtar.c, src/ext/microtar/microtar.h, src/tool/tarball.c
Some of the test releases have names that are too long to fit in the name entry of the tar header, which is 100 characters. For example, this string is 104 characters: 
`orca/test-release-4f124dd346/src/ext/wasm3/platforms/embedded/wm_w600/wasm3/extra/oremark_minimal.wasm.h`
And note that `orca` is 4 characters, which was perfectly cut off, making this extra hard to debug. :) However, there is an additional prefix field that's 155 characters that was added to the tar spec at some point, but microtar just wasn't exposing it. To avoid making too many changes to microtar this change simply exposes the additional prefix field and lets the orca cli tool handle appending the prefix.
=> handle prefix entry for long paths in tar archives

scripts/dev.py
* This paves the way to allow the build process to download a release and try to use the angle/dawn libs from it, if they match the local required commits.
=> include dawn/angle commit json in release

src/graphics/graphics_common.c, src/platform/platform_io_dialog.c, src/ui/ui.c, src/util/memory.c, src/util/memory.h, src/wasm/backend_bytebox.c, src/wasm/backend_wasm3.c
Zero-initialize memory allocated from arenas by default, and provide an explicit uninitialized variant for when usage code takes care of fully initializing the memory.
=> Zero-init arena memory by default

build.zig, samples/ui/src/main.c, src/tool/osx_system.c
* `build.zig` changes add support for building and running samples
* Fixed nested directories not being created correctly in `oc_sys_mkdirs`
* Disabled UBsan for orca tool - some UB is going on when resizing icons and it seems to work fine with UBsan off. I can look into fixing this in a followup.
* Minor compile error fix in the UI sample - I'm guessing zig turns up some strictness settings compared to default clang
Run the samples with:
```
zig build samples
zig build sample-breakout
zig build sample-clock
zig build sample-XXX
```
Note that the bundling step still relies on the user having an orca install in their `PATH`. This is because the current zig build doesn't setup the zig-out directory to mirror how package-sdk sets up the output directory. Ideally in the future we could run …
=> zig build: add support for building, bundling, and running samples

src/app/osx_app.m
* Most of the functions relating to CVDisplayLink have been deprecated, though there isn't an obvious replacement for them. We'll just disable the deprecation for now until we can figure out what the upgrade path is.
=> fix deprecated APIs on macOS 15+
